import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@coldsurfers/ocean-road/global.css'
import { SessionProvider } from 'next-auth/react'
import Header from '@/ui-components/Header'
import IsLoggedInChecker from '@/libs/IsLoggedInChecker'
import { auth } from '@/libs/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  // eslint-disable-next-line no-undef
  children: React.ReactNode
}) {
  const session = await auth()
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Header />
          {children}
          <IsLoggedInChecker />
        </SessionProvider>
      </body>
    </html>
  )
}
