import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@coldsurfers/ocean-road/global.css'
import { SessionProvider } from 'next-auth/react'
import { PropsWithChildren } from 'react'
import { headers } from 'next/headers'
import { redirect } from 'next/navigation'
import Header from '@/ui-components/Header'
import { auth } from '@/libs/auth'
import SideBar from '@/ui-components/SideBar'
import ProtectedRouter from '@/libs/ProtectedRouter'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: PropsWithChildren<{}>) {
  const session = await auth()
  const heads = headers()
  const headerUrl = heads.get('x-url') || ''

  if (!session && !headerUrl.includes('/login')) redirect('/login')
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Header />
          <SideBar />
          {children}
          <ProtectedRouter />
        </SessionProvider>
      </body>
    </html>
  )
}
